import Footer from "./Footer"
import spotifyStock from "../assets/spotify_stock.jpg"
import keyboardStock from "../assets/keyboard_stock.png"
import playlistStock from "../assets/playlist_stock.png"
import logo from "../assets/zel-logo.png"
import "./Landing.css"

export default function Landing({ login }) {
  return (
    <div className="landing">
      <nav className="landing-nav">
        <div className="landing-logo">
          <img src={logo} width="28" height="28" />
          <span>Zeltune</span>
        </div>
        <button className="login-btn" onClick={login}>Login with Spotify</button>
      </nav>

      <section className="hero">
        <div className="hero-content">
          <h1>Your Playlist,<br/>Powered by <span className="highlight">AI</span></h1>
          <p>Connect Spotify, describe your mood, and let artificial intelligence craft the perfect playlist tailored to your taste.</p>
          <button className="hero-cta" onClick={login}>Get Started with Spotify</button>
        </div>
        <div className="hero-visual">
          <div className="hero-placeholder">
            <div className="hero-logo-wrapper">
              <div className="hero-logo-glow"></div>
              <img src={logo} className="hero-logo" width="200" />
            </div>
            <div className="hero-orb hero-orb-1"></div>
            <div className="hero-orb hero-orb-2"></div>
            <div className="hero-orb hero-orb-3"></div>
          </div>
        </div>
      </section>

      <section className="feature-section">
        <div className="feature-inner">
          <div className="feature-image">
            <img src={spotifyStock} alt="Connect Spotify" />
          </div>
          <div className="feature-text">
            <h2>Connect Your Spotify</h2>
            <p>Sign in securely with your Spotify account. We sync your profile and listening history to personalize every playlist recommendation based on your unique taste.</p>
          </div>
        </div>
      </section>

      <section className="feature-section alt">
        <div className="feature-inner reversed">
          <div className="feature-image">
            <img src={keyboardStock} alt="Chat with AI" />
          </div>
          <div className="feature-text">
            <h2>Chat with AI</h2>
            <p>Describe your mood, favorite genres, or the vibe you&apos;re looking for. Our AI understands natural language and builds playlists that match exactly what you want.</p>
          </div>
        </div>
      </section>

      <section className="feature-section">
        <div className="feature-inner">
          <div className="feature-image">
            <img src={playlistStock} alt="Get Playlist" />
          </div>
          <div className="feature-text">
            <h2>Get Your Playlist</h2>
            <p>Receive a custom-curated playlist generated by AI, combining your unique taste with your current request. Save it directly to Spotify with one click.</p>
          </div>
        </div>
      </section>

      <section className="preview-section">
        <div className="preview-content">
          <div className="preview-chat">
            <div className="preview-msg user">
              <div className="preview-bubble user-bubble">I want something upbeat for my morning run</div>
            </div>
            <div className="preview-msg assistant">
              <div className="preview-bubble assistant-bubble">Here&apos;s a high-energy playlist with electronic, hip-hop, and rock tracks to power your run!</div>
            </div>
            <div className="preview-msg user">
              <div className="preview-bubble user-bubble">Add some classic rock too</div>
            </div>
            <div className="preview-msg assistant">
              <div className="preview-bubble assistant-bubble">Updated! Now featuring AC/DC, Queen, and Led Zeppelin alongside your modern tracks. Ready to save?</div>
            </div>
          </div>
          <div className="preview-text">
            <h2 className="section-title">Chat Like You&apos;re Talking to a Friend</h2>
            <p>Powered by Groq AI, Zeltune understands context, remembers your preferences, and creates playlists that match exactly what you&apos;re looking for.</p>
            <ul>
              <li>Natural language understanding</li>
              <li>Context-aware conversations</li>
              <li>Personalized recommendations</li>
              <li>One-click Spotify saving</li>
            </ul>
          </div>
        </div>
      </section>

      <section className="cta-section">
        <h2>Ready to Discover Your Next Favorite Playlist?</h2>
        <p>Connect your Spotify account and start generating playlists with AI.</p>
        <button className="hero-cta" onClick={login}>Login with Spotify</button>
      </section>

      <Footer />
    </div>
  )
}
